name: magic_number
description: "Flutter Project for Magic Number"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # retrofit
  retrofit: '>=4.0.0 <5.0.0'
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.1
  # di
  get_it: ^7.6.4
  # bloc
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # retrofit
  retrofit_generator: '>=7.0.0 <8.0.0'   # required dart >=2.19
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true



